server:
  port: 8080
spring:
  application:
    name: api_gateAway
routes:
  - id: OrderService
    uri: http://localhost:8082/
    predicates:
      - Path=/order/**
  - id: ProductService
    uri: http://localhost:8081/
    predicates:
      - Path=/product/**
